version: '3.7'

services:

  # db is in db folder
  db:
    container_name: db
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # Application Dockerfile is in same folder which is .
  app:
    container_name: app
    build: .
    depends_on:
      - db
