version: '3.7'

services:

  # db is in db folder
  db:
    container_name: db
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
      - "33060:3306"

  # Application Dockerfile is in same folder which is .
  app:
    container_name: app
    build: .
    depends_on:
      - db
    volumes:
      - ./data/:/data
    command:
      - cp /tmp/data/ /data/