name: A workflow for Software Engineering methods
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Compile with Maven
        run: mvn clean package
      - name: Setup network
        run: docker-compose up -d
      - name: Run Integration tests
        run: mvn test -Dtest=IntegrationTests
      - name: Run Unit tests
        run: mvn test -Dtest=UnitTests
      - name: view logs of db
        run: docker logs db; echo "database is ready for connections"
      - name: view logs of app
        run: docker logs app
      - name: Commit and push changes to master branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: 'Update results'
            branch: master